# GitHub Environment Configuration - Production
# This file defines the production environment configuration

name: production
description: Production environment for Taxclusive Next.js application

# Environment variables (non-sensitive)
variables:
  NEXT_PUBLIC_BASE_URL: "https://www.taxclusive.com"
  DOMAIN_NAME: "www.taxclusive.com"
  S3_DEPLOYMENT_BUCKET: "taxclusive-deployments-production"
  
# Protection rules
protection_rules:
  required_reviewers: 2
  wait_timer: 5  # 5 minutes wait before deployment
  prevent_self_review: true

# Deployment branches
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false
  allowed_branches:
    - "main"

# Secrets (to be configured in GitHub Settings -> Environments -> production)
# These are sensitive values that should be set in the GitHub UI:
secrets_documentation:
  # AWS Configuration
  AWS_ACCOUNT_ID: "Your AWS account ID"
  AWS_ACCESS_KEY_ID: "AWS access key for production deployments"
  AWS_SECRET_ACCESS_KEY: "AWS secret key for production deployments"
  
  # SSL Certificate
  SSL_CERTIFICATE_ARN: "ARN of SSL certificate for www.taxclusive.com"
  
  # Email Configuration (AWS SES)
  EMAIL_SENDER_NAME: "Taxclusive"
  EMAIL_SENDER_ADDRESS: "noreply@taxclusive.com"
  EMAIL_RECIPIENT_ADDRESS: "contact@taxclusive.com"
  EMAIL_RECIPIENT_NAME: "Taxclusive Support"
  
  # CMS Configuration
  STRAPI_API_URL: "https://cms.taxclusive.com/api"
  STRAPI_API_TOKEN: "Strapi API token for production environment"
  
  # Analytics & SEO
  GOOGLE_ANALYTICS_ID: "G-PRODUCTION123"
  
  # Security
  CSRF_SECRET: "Strong random string for CSRF protection in production"
  
  # Monitoring
  ALERT_EMAIL: "alerts@taxclusive.com"