# GitHub Environment Configuration - Staging
# This file defines the staging environment configuration

name: staging
description: Staging environment for Taxclusive Next.js application

# Environment variables (non-sensitive)
variables:
  NEXT_PUBLIC_BASE_URL: "https://staging.taxclusive.com"
  DOMAIN_NAME: "staging.taxclusive.com"
  S3_DEPLOYMENT_BUCKET: "taxclusive-deployments-staging"
  
# Protection rules
protection_rules:
  required_reviewers: 0
  wait_timer: 0
  prevent_self_review: false

# Deployment branches
deployment_branch_policy:
  protected_branches: false
  custom_branch_policies: true
  allowed_branches:
    - "develop"
    - "main"

# Secrets (to be configured in GitHub Settings -> Environments -> staging)
# These are sensitive values that should be set in the GitHub UI:
secrets_documentation:
  # AWS Configuration
  AWS_ACCOUNT_ID: "Your AWS account ID"
  AWS_ACCESS_KEY_ID: "AWS access key for staging deployments"
  AWS_SECRET_ACCESS_KEY: "AWS secret key for staging deployments"
  
  # SSL Certificate
  SSL_CERTIFICATE_ARN: "ARN of SSL certificate for staging.taxclusive.com"
  
  # Email Configuration (AWS SES)
  EMAIL_SENDER_NAME: "Taxclusive Staging"
  EMAIL_SENDER_ADDRESS: "noreply-staging@taxclusive.com"
  EMAIL_RECIPIENT_ADDRESS: "dev@taxclusive.com"
  EMAIL_RECIPIENT_NAME: "Taxclusive Dev Team"
  
  # CMS Configuration
  STRAPI_API_URL: "https://staging-cms.taxclusive.com/api"
  STRAPI_API_TOKEN: "Strapi API token for staging environment"
  
  # Analytics & SEO
  GOOGLE_ANALYTICS_ID: "G-STAGING123"
  
  # Security
  CSRF_SECRET: "Random string for CSRF protection in staging"
  
  # Monitoring
  ALERT_EMAIL: "alerts-staging@taxclusive.com"